### PR TITLE
Add a onCurrentUser prop method to retrieve current logged-in user.

### PR DESCRIPTION
**Pull request by rmoscuba**
Add a onCurrentUser property method to retrieve the already logged-in user information when the component is mounted.

Also added a "offline" property, this way we can get a token we can use to initiate oauth2 flow in backend onSuccess.

Have a nice day.

### CODE REVIEW

**Comment by lwagf** [comment]
+1 I was looking for functionality like this

**Comment by rmartide** [comment]
Hi,

Thanks for contributing, I checked the changes and it looks good but I need to do some manual testing.

For now I will merge it but I won't publish it until tomorrow or the day after tomorrow since I am a bit bussy on weekdays.

Regards.

**Comment by rmartide** [comment]
@rmoscuba I did some testing and I have one question since I don't want to clutter the button with that many callbacks.

I understand the onCurrentUser, it could be done injecting the plugin but it seems like a feature that could be used many times.

The offline property is the one I'm not that sure about, for things that specific you can always inject the plugin and get access to the full auth api. Is this something that you think should have that much priority?

This brings another question. 

`GoogleAuth['grantOfflineAccess']({'redirect_uri': 'postmessage'})`

Why redirect_uri and no other params?

**Comment by rmoscuba** [comment]
Hi @rmartide

Sorry about the delay.

The priority is onCurrentUser. But I think offline is good to have it since sometimes we need a token for get offline access on behalf of the user.

The documentation on the parameters is at:

https://developers.google.com/identity/sign-in/web/reference#gapiauth2offlineaccessoptions. 

Actually, I am not really sure about {'redirect_uri': 'postmessage'} now I think it is for the backend oauth2 flow. No need to be passed in front end.

Thanks!

Rodolfo

**Comment by rmartide** [comment]
Hello @rmoscuba,

I've decided that for now, since I don't have much time to publish first the onCurrentUser functionality.

I'm thinking on adding the offline but instead of with just with redirect_uri to give the option to add several params. I need to study it first.

I'll try to work on it on the weekend.

The changes are up online.

Cheers.

**Pull request merged**
